import {
  BedroomZoneOption,
  BedroomContextOption,
  BedroomPoseOption,
  BedroomCameraOption,
  BedroomLightingOption,
  BedroomPropOption,
  BedroomClothingOption,
  BedroomHairstyleOption,
  BedroomExpressionOption,
  SaudiBedroomDetailOption,
} from './types';

export const BEDROOM_ZONES: BedroomZoneOption[] = [
  {
    id: 'on_the_bed',
    name: 'On the bed',
    description: 'Relaxed on a comfortable bed with soft textured duvet, plush pillows, and an upholstered or wooden headboard.',
    bedroomDetails: [
      'Soft rumpled white cotton or linen duvet and textured throw blanket',
      'Plush sleeping pillows stacked against the headboard',
      'Warm bedside nightstand with small lamp and charging cable nearby',
      'Cozy, authentic private bedroom atmosphere with ambient room depth in background',
    ],
    supportedContextIds: ['propped_against_headboard', 'lying_back_on_bed', 'sitting_on_bed_edge'],
    defaultContextId: 'propped_against_headboard',
    defaultLightingId: 'warm_nightstand_lamp',
    defaultPoseId: 'propped_bed_one_handed',
    defaultCameraId: 'front_camera_eye_level',
    isStandingZone: false,
  },
  {
    id: 'bedroom_window',
    name: 'By the bedroom window',
    description: 'Beside the bedroom window, soft natural daylight filtering through sheer curtains.',
    bedroomDetails: [
      'Floor-to-ceiling or large bedroom window with translucent sheer white curtains',
      'Subtle daylight filtered through curtain fabric creating soft natural wrap',
      'Bedroom floor and interior room depth visible softly in background',
      'Cozy indoor bedroom atmosphere with calm natural illumination',
    ],
    supportedContextIds: ['standing_by_curtain', 'sitting_by_window_sill'],
    defaultContextId: 'standing_by_curtain',
    defaultLightingId: 'natural_window_daylight',
    defaultPoseId: 'standing_next_to_window',
    defaultCameraId: 'front_camera_eye_level',
    isStandingZone: true,
  },
  {
    id: 'bedroom_mirror',
    name: 'In front of the bedroom mirror',
    description: 'Standing in front of the bedroom vanity dresser mirror or full-length wardrobe mirror, capturing a casual mirror selfie.',
    bedroomDetails: [
      'Clean full-length bedroom mirror or vanity mirror reflecting the room interior',
      'Background in reflection shows the cozy unmade bed, bedroom rug, and wooden furniture',
      'Smartphone clearly visible in hand, showing the reflection',
      'Authentic bedroom mirror reflection with true room perspective',
    ],
    supportedContextIds: ['standing_mirror_full_length_ctx', 'standing_vanity_mirror'],
    defaultContextId: 'standing_mirror_full_length_ctx',
    defaultLightingId: 'overhead_room_light',
    defaultPoseId: 'standing_mirror_full_length',
    defaultCameraId: 'mirror_selfie_handheld',
    isStandingZone: true,
  },
  {
    id: 'bedroom_middle',
    name: 'In the middle of the bedroom',
    description: 'Standing freely in the open central space of the bedroom, bed and room decor visible in the soft background.',
    bedroomDetails: [
      'Open carpeted or wooden bedroom floor area',
      'Unmade bed with pillows softly out of focus in the background',
      'Warm residential bedroom wall color and cozy interior atmosphere',
      'Natural arm-length wide-angle selfie perspective capturing subject and room',
    ],
    supportedContextIds: ['standing_middle_bedroom_ctx'],
    defaultContextId: 'standing_middle_bedroom_ctx',
    defaultLightingId: 'overhead_room_light',
    defaultPoseId: 'standing_middle_of_bedroom',
    defaultCameraId: 'front_camera_eye_level',
    isStandingZone: true,
  },
  {
    id: 'bedroom_wardrobe',
    name: 'Beside the bedroom wardrobe/closet',
    description: 'Standing beside the large wooden bedroom wardrobe or closet doors.',
    bedroomDetails: [
      'Tall bedroom wardrobe or built-in closet with clean wood-grain paneling',
      'Part of the bedside table and bedroom wall visible to one side',
      'Casual indoor lifestyle bedroom setting',
      'Soft diffused indoor light falling across clothing and wardrobe surface',
    ],
    supportedContextIds: ['standing_wardrobe_ctx'],
    defaultContextId: 'standing_wardrobe_ctx',
    defaultLightingId: 'overhead_room_light',
    defaultPoseId: 'standing_beside_wardrobe',
    defaultCameraId: 'front_camera_eye_level',
    isStandingZone: true,
  },
  {
    id: 'bedroom_door',
    name: 'Near the bedroom door',
    description: 'Standing near the closed bedroom door, showing interior bedroom wall and door trim.',
    bedroomDetails: [
      'Clean closed interior bedroom door with brushed handle',
      'Neutral painted bedroom drywall and light switch',
      'Bed and nightstand softly receding in the background',
      'Spontaneous snapshot taken before heading out or after entering the room',
    ],
    supportedContextIds: ['standing_door_ctx'],
    defaultContextId: 'standing_door_ctx',
    defaultLightingId: 'overhead_room_light',
    defaultPoseId: 'standing_near_bedroom_door',
    defaultCameraId: 'front_camera_eye_level',
    isStandingZone: true,
  },
  {
    id: 'bedroom_chair',
    name: 'Relaxing on a bedroom chair',
    description: 'Sitting back in a comfortable upholstered accent armchair or desk chair in the corner of the bedroom.',
    bedroomDetails: [
      'Deep cushioned accent armchair or contemporary desk chair',
      'Bed and warm bedside table softly out of focus in the background',
      'Textured throw pillow resting behind the lower back',
      'Cozy private room setting with quiet indoor ambiance',
    ],
    supportedContextIds: ['lounging_accent_armchair', 'bedroom_desk_chair'],
    defaultContextId: 'lounging_accent_armchair',
    defaultLightingId: 'warm_nightstand_lamp',
    defaultPoseId: 'chair_lounging_selfie',
    defaultCameraId: 'front_camera_eye_level',
    isStandingZone: false,
  },
];

export const BEDROOM_CONTEXTS: BedroomContextOption[] = [
  // Bed contexts
  {
    id: 'propped_against_headboard',
    name: 'Propped against headboard pillows',
    description: 'Sitting up comfortably in bed with back supported by stacked pillows against the headboard.',
    isMirrorContext: false,
    isStandingContext: false,
    allowedZoneIds: ['on_the_bed'],
    defaultPoseId: 'propped_bed_one_handed',
    defaultCameraId: 'front_camera_eye_level',
    allowedPoseIds: ['propped_bed_one_handed', 'headboard_casual_tilt', 'hand_on_cheek_bed'],
    allowedCameraIds: ['front_camera_eye_level', 'front_camera_high_angle'],
    allowedPropIds: ['prop_none', 'prop_mug_tea', 'prop_airpods_case', 'prop_reading_book'],
  },
  {
    id: 'lying_back_on_bed',
    name: 'Lying back casually on the mattress',
    description: 'Resting flat or slightly elevated on the bed, holding smartphone overhead at arm distance.',
    isMirrorContext: false,
    isStandingContext: false,
    allowedZoneIds: ['on_the_bed'],
    defaultPoseId: 'lying_overhead_selfie',
    defaultCameraId: 'front_camera_high_angle',
    allowedPoseIds: ['lying_overhead_selfie', 'lying_pillow_rest'],
    allowedCameraIds: ['front_camera_high_angle', 'front_camera_eye_level'],
    allowedPropIds: ['prop_none', 'prop_airpods_case'],
  },
  {
    id: 'sitting_on_bed_edge',
    name: 'Sitting on the edge of the mattress',
    description: 'Perched on the side edge of the bed, feet on the floor rug, holding smartphone up casually.',
    isMirrorContext: false,
    isStandingContext: false,
    allowedZoneIds: ['on_the_bed'],
    defaultPoseId: 'bed_edge_casual_sit',
    defaultCameraId: 'front_camera_eye_level',
    allowedPoseIds: ['bed_edge_casual_sit', 'bed_edge_forward_lean'],
    allowedCameraIds: ['front_camera_eye_level', 'front_camera_chest_tilt'],
    allowedPropIds: ['prop_none', 'prop_mug_tea', 'prop_airpods_case'],
  },

  // Window contexts
  {
    id: 'standing_by_curtain',
    name: 'Standing right next to the bedroom window',
    description: 'Standing beside the bedroom window with translucent curtains in background, front-camera selfie with arm extended.',
    isMirrorContext: false,
    isStandingContext: true,
    allowedZoneIds: ['bedroom_window'],
    defaultPoseId: 'standing_next_to_window',
    defaultCameraId: 'front_camera_eye_level',
    allowedPoseIds: ['standing_next_to_window', 'standing_window_quarter_turn'],
    allowedCameraIds: ['front_camera_eye_level', 'front_camera_high_angle'],
    allowedPropIds: ['prop_none', 'prop_mug_tea'],
  },
  {
    id: 'sitting_by_window_sill',
    name: 'Seated on windowsill bench looking toward room',
    description: 'Sitting on the low bedroom window ledge or bench, daylight behind and beside the subject.',
    isMirrorContext: false,
    isStandingContext: false,
    allowedZoneIds: ['bedroom_window'],
    defaultPoseId: 'window_sill_sit',
    defaultCameraId: 'front_camera_eye_level',
    allowedPoseIds: ['window_sill_sit'],
    allowedCameraIds: ['front_camera_eye_level', 'front_camera_chest_tilt'],
    allowedPropIds: ['prop_none', 'prop_mug_tea', 'prop_reading_book'],
  },

  // Mirror contexts
  {
    id: 'standing_mirror_full_length_ctx',
    name: 'Standing in front of full-length bedroom mirror',
    description: 'Standing in front of a full-length bedroom mirror, mirror selfie with smartphone clearly visible in hand.',
    isMirrorContext: true,
    isStandingContext: true,
    allowedZoneIds: ['bedroom_mirror'],
    defaultPoseId: 'standing_mirror_full_length',
    defaultCameraId: 'mirror_selfie_handheld',
    allowedPoseIds: ['standing_mirror_full_length', 'standing_mirror_casual_lean'],
    allowedCameraIds: ['mirror_selfie_handheld'],
    allowedPropIds: ['prop_none'],
  },
  {
    id: 'standing_vanity_mirror',
    name: 'Standing in front of vanity dresser mirror',
    description: 'Standing before the bedroom vanity mirror, phone held up to capture torso reflection and room ambiance.',
    isMirrorContext: true,
    isStandingContext: true,
    allowedZoneIds: ['bedroom_mirror'],
    defaultPoseId: 'standing_mirror_full_length',
    defaultCameraId: 'mirror_selfie_handheld',
    allowedPoseIds: ['standing_mirror_full_length', 'standing_mirror_casual_lean'],
    allowedCameraIds: ['mirror_selfie_handheld'],
    allowedPropIds: ['prop_none', 'prop_mug_tea'],
  },

  // Middle of bedroom context
  {
    id: 'standing_middle_bedroom_ctx',
    name: 'Standing in the middle of the bedroom',
    description: 'Standing in the middle of the bedroom with the bed softly blurred in the background, arm extended holding phone.',
    isMirrorContext: false,
    isStandingContext: true,
    allowedZoneIds: ['bedroom_middle'],
    defaultPoseId: 'standing_middle_of_bedroom',
    defaultCameraId: 'front_camera_eye_level',
    allowedPoseIds: ['standing_middle_of_bedroom'],
    allowedCameraIds: ['front_camera_eye_level', 'front_camera_high_angle'],
    allowedPropIds: ['prop_none', 'prop_mug_tea', 'prop_airpods_case'],
  },

  // Wardrobe context
  {
    id: 'standing_wardrobe_ctx',
    name: 'Standing beside the bedroom wardrobe/closet',
    description: 'Standing beside the bedroom wardrobe, front-camera selfie with arm extended holding the phone.',
    isMirrorContext: false,
    isStandingContext: true,
    allowedZoneIds: ['bedroom_wardrobe'],
    defaultPoseId: 'standing_beside_wardrobe',
    defaultCameraId: 'front_camera_eye_level',
    allowedPoseIds: ['standing_beside_wardrobe'],
    allowedCameraIds: ['front_camera_eye_level', 'front_camera_high_angle'],
    allowedPropIds: ['prop_none', 'prop_airpods_case'],
  },

  // Door context
  {
    id: 'standing_door_ctx',
    name: 'Standing near the closed bedroom door',
    description: 'Standing near the closed bedroom door, interior wall background, front-camera selfie, arm extended holding phone.',
    isMirrorContext: false,
    isStandingContext: true,
    allowedZoneIds: ['bedroom_door'],
    defaultPoseId: 'standing_near_bedroom_door',
    defaultCameraId: 'front_camera_eye_level',
    allowedPoseIds: ['standing_near_bedroom_door'],
    allowedCameraIds: ['front_camera_eye_level', 'front_camera_chest_tilt'],
    allowedPropIds: ['prop_none', 'prop_airpods_case'],
  },

  // Chair contexts
  {
    id: 'lounging_accent_armchair',
    name: 'Curled up in cozy bedroom armchair',
    description: 'Settled deeply into the cushioned accent chair in the bedroom corner with duvet or throw blanket.',
    isMirrorContext: false,
    isStandingContext: false,
    allowedZoneIds: ['bedroom_chair'],
    defaultPoseId: 'chair_lounging_selfie',
    defaultCameraId: 'front_camera_eye_level',
    allowedPoseIds: ['chair_lounging_selfie', 'chair_elbow_lean'],
    allowedCameraIds: ['front_camera_eye_level', 'front_camera_high_angle'],
    allowedPropIds: ['prop_none', 'prop_mug_tea', 'prop_reading_book'],
  },
  {
    id: 'bedroom_desk_chair',
    name: 'Sitting relaxed at bedroom desk',
    description: 'Turned slightly away from the bedroom study desk, elbow resting near table edge.',
    isMirrorContext: false,
    isStandingContext: false,
    allowedZoneIds: ['bedroom_chair'],
    defaultPoseId: 'chair_elbow_lean',
    defaultCameraId: 'front_camera_eye_level',
    allowedPoseIds: ['chair_elbow_lean', 'chair_lounging_selfie'],
    allowedCameraIds: ['front_camera_eye_level', 'front_camera_chest_tilt'],
    allowedPropIds: ['prop_none', 'prop_mug_tea', 'prop_airpods_case'],
  },
];

export const BEDROOM_POSES: BedroomPoseOption[] = [
  // --- 5 SPATIAL STANDING POSES (EXACT USER REQUIREMENTS) ---
  {
    id: 'standing_mirror_full_length',
    name: 'Standing in front of a full-length bedroom mirror, mirror selfie. The smartphone is clearly visible in hand, showing the reflection.',
    shortLabel: 'Standing Mirror Selfie',
    description: 'Standing in front of a full-length bedroom mirror, mirror selfie. The smartphone is clearly visible in hand, showing the reflection.',
    biomechanics: 'Body weight balanced naturally on both feet; one hand holding the smartphone at chest height facing the mirror glass, screen and phone case reflected clearly; free hand resting in shorts pocket or loosely at the side.',
    postureType: 'standing',
    requiresMirror: true,
    spatialLocation: 'in front of a full-length bedroom mirror',
  },
  {
    id: 'standing_middle_of_bedroom',
    name: 'Standing in the middle of the bedroom, the bed is visible in the background out of focus, front-camera selfie, arm extended holding the phone.',
    shortLabel: 'Standing Middle of Bedroom',
    description: 'Standing in the middle of the bedroom, the bed is visible in the background out of focus, front-camera selfie, arm extended holding the phone.',
    biomechanics: 'Upright standing posture in the center of the room; one arm extended forward at ~60cm distance holding the smartphone at eye level; one shoulder subtly raised from reaching; free arm resting naturally by hip.',
    postureType: 'standing',
    requiresMirror: false,
    spatialLocation: 'in the middle of the bedroom with the bed softly visible in the background',
  },
  {
    id: 'standing_next_to_window',
    name: 'Standing right next to the bedroom window, window curtains in the background, front-camera selfie, arm extended holding the phone.',
    shortLabel: 'Standing by Window',
    description: 'Standing right next to the bedroom window, window curtains in the background, front-camera selfie, arm extended holding the phone.',
    biomechanics: 'Standing beside the bedroom window frame; one arm extended forward holding the smartphone capturing natural daylight washing over face and torso; sheer window curtains visible in the background.',
    postureType: 'standing',
    requiresMirror: false,
    spatialLocation: 'right next to the bedroom window with curtains in background',
  },
  {
    id: 'standing_beside_wardrobe',
    name: 'Standing beside the bedroom wardrobe/closet, casual indoor lifestyle composition, front-camera selfie, arm extended holding the phone.',
    shortLabel: 'Standing Beside Wardrobe',
    description: 'Standing beside the bedroom wardrobe/closet, casual indoor lifestyle composition, front-camera selfie, arm extended holding the phone.',
    biomechanics: 'Casual standing stance next to the wooden wardrobe/closet doors; smartphone held forward at eye level at comfortable arm length (~55cm); relaxed posture.',
    postureType: 'standing',
    requiresMirror: false,
    spatialLocation: 'beside the bedroom wardrobe and closet doors',
  },
  {
    id: 'standing_near_bedroom_door',
    name: 'Standing near the closed bedroom door, interior wall background, front-camera selfie, arm extended holding the phone.',
    shortLabel: 'Standing Near Door',
    description: 'Standing near the closed bedroom door, interior wall background, front-camera selfie, arm extended holding the phone.',
    biomechanics: 'Standing near the bedroom doorway; smartphone held at chest/eye level tilted slightly forward; neutral painted bedroom wall and door panel visible in the background.',
    postureType: 'standing',
    requiresMirror: false,
    spatialLocation: 'near the closed bedroom door against interior wall',
  },

  // Auxiliary standing poses
  {
    id: 'standing_mirror_casual_lean',
    name: 'Leaning casually against vanity wall (Mirror selfie)',
    shortLabel: 'Leaning Mirror Selfie',
    description: 'Shoulder resting casually against the bedroom vanity wall, holding phone tilted in front of mirror with relaxed casual posture.',
    biomechanics: 'Body weight gently supported against vanity frame; smartphone held firmly with one hand facing the mirror glass.',
    postureType: 'standing',
    requiresMirror: true,
    spatialLocation: 'in front of the bedroom vanity mirror',
  },
  {
    id: 'standing_window_quarter_turn',
    name: 'Quarter turn at bedroom window (Side daylight)',
    shortLabel: 'Window Quarter Turn',
    description: 'Body angled slightly toward bedroom interior while head turns back toward window light, arm extended holding phone.',
    biomechanics: 'Gentle neck twist and balanced hip alignment; soft curtain fabric brushing arm; phone held at 55cm.',
    postureType: 'standing',
    requiresMirror: false,
    spatialLocation: 'beside the bedroom window',
  },

  // --- BED POSES (SITTING & LYING) ---
  {
    id: 'propped_bed_one_handed',
    name: 'Propped in bed against pillows (Arm extended)',
    shortLabel: 'Propped in Bed',
    description: 'Upper torso resting comfortably against headboard pillows; right arm extended forward holding the smartphone at 60cm distance, left hand resting loosely on the duvet.',
    biomechanics: 'Right shoulder slightly elevated and pulled forward by phone reach; relaxed upper body grounded into bed mattress.',
    postureType: 'sitting',
    requiresMirror: false,
    spatialLocation: 'propped against pillows on the bed',
  },
  {
    id: 'headboard_casual_tilt',
    name: 'Head tilted against pillow (Arm extended)',
    shortLabel: 'Head Tilted on Pillow',
    description: 'Head resting gently sideways against a fluffy white pillow, right hand holding the smartphone slightly above face level, free hand tucked under sheet.',
    biomechanics: 'Candid relaxed neck angle with natural contact indent in the pillow fabric; steady one-handed smartphone grip.',
    postureType: 'sitting',
    requiresMirror: false,
    spatialLocation: 'resting on pillows on the bed',
  },
  {
    id: 'hand_on_cheek_bed',
    name: 'Elbow propped on mattress (Hand near cheek)',
    shortLabel: 'Elbow Propped on Bed',
    description: 'Left elbow propped up on the bed supporting cheek/chin, right arm extended holding the smartphone at eye level.',
    biomechanics: 'Asymmetric intimate posture; realistic skin compression where palm touches cheek; natural phone reach.',
    postureType: 'sitting',
    requiresMirror: false,
    spatialLocation: 'resting on the bed mattress',
  },
  {
    id: 'lying_overhead_selfie',
    name: 'Lying on back (Overhead arm extension)',
    shortLabel: 'Lying on Back',
    description: 'Lying flat on bed with head sunk into soft pillow, holding phone directly overhead with one arm at arm length, looking up into front camera.',
    biomechanics: 'Shoulder braced against mattress; arm reaching directly upward with vertical perspective; soft fabric folds around shoulders.',
    postureType: 'lying',
    requiresMirror: false,
    spatialLocation: 'lying flat on the bed',
  },
  {
    id: 'lying_pillow_rest',
    name: 'Lying on side (Close-up pillow perspective)',
    shortLabel: 'Lying on Side',
    description: 'Curled on side on the mattress, head half-buried in pillow, one arm bent holding phone just 45cm away for a cozy, sleepy snapshot.',
    biomechanics: 'Weight resting on side of torso and hip; intimate close-range arm extension with slight natural wide-angle distortion.',
    postureType: 'lying',
    requiresMirror: false,
    spatialLocation: 'lying on side on the bed',
  },
  {
    id: 'bed_edge_casual_sit',
    name: 'Seated on bed edge (Elbow on knee)',
    shortLabel: 'Seated on Bed Edge',
    description: 'Sitting on the side edge of the bed with knees bent, left forearm resting on thigh, right hand holding the phone forward at eye level.',
    biomechanics: 'Grounded seated posture; slight forward torso lean with authentic shoulder mechanics.',
    postureType: 'sitting',
    requiresMirror: false,
    spatialLocation: 'seated on the edge of the bed mattress',
  },
  {
    id: 'bed_edge_forward_lean',
    name: 'Seated on bed edge (Two-handed grip)',
    shortLabel: 'Two-Handed Bed Sit',
    description: 'Sitting on mattress edge holding smartphone with both hands centered in front of chest, smiling casually at screen.',
    biomechanics: 'Both elbows bent and tucked close to ribcage, thumbs resting on screen corners.',
    postureType: 'sitting',
    requiresMirror: false,
    spatialLocation: 'seated on the edge of the bed',
  },
  {
    id: 'window_sill_sit',
    name: 'Sitting on windowsill bench (Casual recline)',
    shortLabel: 'Windowsill Sit',
    description: 'Sitting sideways on low bedroom window bench with one knee drawn up slightly, holding phone with one hand forward.',
    biomechanics: 'Comfortable seated balance against window reveal; free hand resting on knee.',
    postureType: 'sitting',
    requiresMirror: false,
    spatialLocation: 'sitting on the bedroom window bench',
  },
  {
    id: 'chair_lounging_selfie',
    name: 'Lounging in armchair (Arm on armrest)',
    shortLabel: 'Armchair Lounge',
    description: 'Settled deep into the bedroom accent chair, elbow propped on the chair armrest, holding smartphone forward at 55cm distance.',
    biomechanics: 'Relaxed seated slump into chair cushions; forearm securely supported by padded armrest.',
    postureType: 'sitting',
    requiresMirror: false,
    spatialLocation: 'lounging in the bedroom armchair',
  },
  {
    id: 'chair_elbow_lean',
    name: 'Seated chair forward lean (Candid gaze)',
    shortLabel: 'Chair Forward Lean',
    description: 'Leaning forward in chair with elbows propped, holding smartphone at chin level tilted up slightly.',
    biomechanics: 'Engaged candid posture; head tilted slightly toward phone camera lens.',
    postureType: 'sitting',
    requiresMirror: false,
    spatialLocation: 'seated forward in the bedroom chair',
  },
];

export const BEDROOM_CAMERAS: BedroomCameraOption[] = [
  {
    id: 'front_camera_eye_level',
    name: 'Smartphone Front Camera (Eye-Level Handheld)',
    perspective: 'Handheld at direct eye-level, roughly 60cm arm distance. Authentic 24mm–26mm front-camera wide field of view.',
    armReach: 'One arm extended forward-right, elbow slightly unlocked; natural slight wide-angle perspective on forearm.',
    phoneGrip: 'One-handed grip with pinky supporting the bottom phone edge and thumb resting near the screen shutter button.',
    opticalNote: 'Gentle natural wide-angle facial rendering; true-to-life proportions without DSLR compression or artificial bokeh.',
    isMirrorMode: false,
  },
  {
    id: 'front_camera_high_angle',
    name: 'Smartphone Front Camera (High-Angle Downward Tilt)',
    perspective: 'Handheld slightly above brow line, tilted down 15–20 degrees toward face. Defines clean jawline and captures room depth.',
    armReach: 'Arm raised overhead or slightly forward at ~55cm distance.',
    phoneGrip: 'Secure one-handed grip, phone tilted downward directly toward subject.',
    opticalNote: 'Classic bedroom selfie geometry; room interior forms the backdrop.',
    isMirrorMode: false,
  },
  {
    id: 'front_camera_chest_tilt',
    name: 'Smartphone Front Camera (Low-Chest Upward Tilt)',
    perspective: 'Phone held near upper chest level, tilted slightly upward (10 degrees), capturing room ceiling and bedroom ambiance.',
    armReach: 'Elbow bent closer to body, phone held at ~50cm distance.',
    phoneGrip: 'Casual one-handed or two-handed grip at chest height.',
    opticalNote: 'Spontaneous candid perspective; captures vertical bedroom depth and overhead light softly.',
    isMirrorMode: false,
  },
  {
    id: 'mirror_selfie_handheld',
    name: 'Smartphone Mirror Reflection (Handheld)',
    perspective: 'Rear camera pointed into bedroom mirror from chest/waist height, capturing reflection of subject holding phone.',
    armReach: 'One hand holding smartphone firmly at chest level, screen and phone case visible in reflection.',
    phoneGrip: 'One-handed grip framing phone body, fingers wrapped naturally around side rails of phone case.',
    opticalNote: 'Crisp mirror reflection showing full torso, clothing fit, unmade bed, and bedroom interior behind.',
    isMirrorMode: true,
  },
];

export const BEDROOM_LIGHTING: BedroomLightingOption[] = [
  {
    id: 'bright_morning_daylight',
    name: 'Bright morning daylight streaming through the window, casting natural directional light and soft shadows across the face.',
    timeOfDay: 'Morning',
    lightSource: 'Bright morning daylight streaming through the window',
    shadowDescription: 'Natural directional light and soft shadows cast across the face and upper torso; natural highlight roll-off.',
    atmosphere: 'Calm morning bedroom tranquility with clean natural daylight (5500K) filling the room.',
  },
  {
    id: 'warm_tungsten_nightstand_lamp',
    name: 'Warm tungsten nightstand lamp lighting, cozy evening indoor atmosphere with deep ambient shadows.',
    timeOfDay: 'Evening / Night',
    lightSource: 'Warm tungsten nightstand lamp on bedside table',
    shadowDescription: 'Deep ambient shadows filling bedroom corners with warm amber illumination caressing skin and headboard.',
    atmosphere: 'Cozy evening indoor atmosphere with deep ambient shadows and warm domestic intimacy.',
  },
  {
    id: 'pitch_dark_screen_glow',
    name: 'Pitch dark room illuminated solely by the cool blue light emitting from the smartphone screen, casting dramatic screen-glow on the face.',
    timeOfDay: 'Late Night (Pitch Dark)',
    lightSource: 'Cool blue light emitting solely from the handheld smartphone screen 45cm away',
    shadowDescription: 'Dramatic specular screen-glow casting high contrast illumination on face, while background falls completely into darkness.',
    atmosphere: 'Late-night phone browsing in pitch dark room; ambient room details fade into deep shadow, no daytime or window light.',
  },
  {
    id: 'overhead_room_light',
    name: 'Diffused overhead room ceiling light, even and balanced indoor illumination.',
    timeOfDay: 'Evening / Anytime',
    lightSource: 'Standard diffused warm-neutral flush-mount ceiling fixture in the center of the bedroom ceiling',
    shadowDescription: 'Even, soft downward room ambient light with subtle contact shadows beneath jawline and furniture edges.',
    atmosphere: 'Realistic everyday bedroom brightness; authentic casual camera roll lighting with true-to-life interior tone.',
  },
];

export const BEDROOM_PROPS: BedroomPropOption[] = [
  {
    id: 'prop_none',
    name: 'Hands Free (Resting on Duvet / In Pocket)',
    description: 'Free hand resting naturally on the bed duvet, pillow, or tucked casually into shorts pocket.',
  },
  {
    id: 'prop_mug_tea',
    name: 'Warm Ceramic Coffee / Tea Mug',
    description: 'Handcrafted ceramic mug of hot tea or coffee resting on the nightstand or held loosely in free hand.',
  },
  {
    id: 'prop_airpods_case',
    name: 'Single Wireless Earbud in Ear',
    description: 'Small white wireless earbud in one ear, listening to music or voice note in bedroom.',
  },
  {
    id: 'prop_reading_book',
    name: 'Open Paperback Book Nearby',
    description: 'A paperback book resting open on the bed sheets or nearby bedside table.',
  },
];

export const BEDROOM_CLOTHING: BedroomClothingOption[] = [
  // --- 5 EXPANDED CASUAL T-SHIRTS & SHORTS (EXACT USER REQUIREMENTS) ---
  {
    id: 'clothing_oversized_tshirt_shorts',
    name: 'Oversized cozy casual t-shirt and comfortable cotton lounge shorts',
    category: 'tshirt_shorts',
    description: 'An oversized cozy casual t-shirt in soft washed cotton paired with comfortable cotton lounge shorts for effortless relaxed indoor styling.',
  },
  {
    id: 'clothing_athletic_tshirt_shorts',
    name: 'Fitted athletic t-shirt and short sports shorts',
    category: 'tshirt_shorts',
    description: 'A fitted breathable athletic t-shirt with sporty short training shorts, athletic casual bedroom look.',
  },
  {
    id: 'clothing_classic_tshirt_denim_shorts',
    name: 'Classic plain cotton t-shirt and casual denim shorts',
    category: 'tshirt_shorts',
    description: 'A classic plain crewneck cotton t-shirt paired with relaxed-fit casual denim shorts.',
  },
  {
    id: 'clothing_matching_summer_sleepwear',
    name: 'Matching summer sleepwear set, short-sleeve top and shorts',
    category: 'tshirt_shorts',
    description: 'A coordinated matching summer sleepwear set featuring a lightweight short-sleeve crewneck top and matching soft shorts.',
  },
  {
    id: 'clothing_sleeveless_tank_shorts',
    name: 'Sleeveless tank top and lightweight breathable shorts',
    category: 'tshirt_shorts',
    description: 'A clean sleeveless ribbed tank top paired with lightweight breathable home shorts for warm comfortable indoor lounging.',
  },

  // Additional popular loungewear
  {
    id: 'clothing_bedroom_soft_tee_shorts',
    name: 'Soft Grey Lounge Tee & Jersey Shorts',
    category: 'loungewear',
    description: 'Oversized heather-grey washed cotton crewneck lounge t-shirt with relaxed dark jersey shorts; effortless everyday home comfort.',
  },
  {
    id: 'clothing_minimal_white_undershirt',
    name: 'Classic White Cotton Undershirt (Faneela)',
    category: 'loungewear',
    description: 'Classic crisp white ribbed cotton crewneck undershirt (faneela) with relaxed lounge shorts; iconic everyday home casual.',
  },
  {
    id: 'clothing_relaxed_thobe_nom',
    name: 'Casual Lightweight Home Thobe (Thobe Nom)',
    category: 'casual_home',
    description: 'Relaxed, lightweight soft cotton home thobe in neutral slate or beige, unbuttoned at collar for easy bedroom comfort.',
  },
  {
    id: 'clothing_hoodie_sweatpants',
    name: 'Cozy Fleece Hoodie & Sweatpants',
    category: 'loungewear',
    description: 'Soft oversized oatmeal/sand fleece pullover hoodie paired with matching relaxed sweatpants; cozy winter bedroom lounging.',
  },
  {
    id: 'clothing_cotton_pajama_set',
    name: 'Soft Striped Cotton Pajama Set',
    category: 'pajamas',
    description: 'Comfortable navy and white or charcoal pinstripe cotton button-up pajama shirt with relaxed pajama bottoms.',
  },
];

export const BEDROOM_HAIRSTYLES: BedroomHairstyleOption[] = [
  {
    id: 'hair_casual_bedhead_stubble',
    name: 'Casual Tousled Bedhead & Light Stubble',
    description: 'Natural tousled dark hair with subtle sleep-textured volume and soft 2-day beard stubble along jawline.',
  },
  {
    id: 'hair_low_fade_textured',
    name: 'Low-Fade Textured Crop & Trimmed Stubble',
    description: 'Clean modern low skin taper on sides with textured natural dark crop on top and neatly groomed short stubble.',
  },
  {
    id: 'hair_buzz_fade',
    name: 'Clean Buzz Cut & Defined Shadow',
    description: 'Minimalist clean buzz fade with sharp temple line and faint natural shadow along jawline.',
  },
  {
    id: 'hair_wavy_dark_messy',
    name: 'Wavy Dark Hair (Relaxed Home Style)',
    description: 'Naturally wavy dark hair falling effortlessly over forehead with relaxed, unstyled bedroom texture and soft mustache/stubble.',
  },
];

export const BEDROOM_EXPRESSIONS: BedroomExpressionOption[] = [
  // --- 3 NEW CANDID FACIAL EXPRESSIONS (EXACT USER REQUIREMENTS) ---
  {
    id: 'exp_sleepy_candid_morning',
    name: 'Sleepy, candid morning smile with relaxed, heavy eyelids.',
    description: 'Sleepy, candid morning smile with relaxed, heavy eyelids, projecting quiet morning ease and contentment.',
    microExpression: 'Softly relaxed lips, subtle crinkle around eyes, peaceful resting facial muscle tone, heavy relaxed eyelids.',
  },
  {
    id: 'exp_serious_focused_mirror',
    name: 'Serious, focused expression, looking directly at the smartphone screen.',
    description: 'Serious, focused expression, looking directly at the smartphone screen while framing the selfie.',
    microExpression: 'Composed, direct dark eyes locked onto phone display, neutral mouth, calm confident brow.',
  },
  {
    id: 'exp_getting_ready_confident',
    name: "Candid 'getting ready to go out' look, checking appearance with a subtle, confident smirk.",
    description: "Candid 'getting ready to go out' look, checking appearance with a subtle, confident smirk in front of the camera.",
    microExpression: 'One corner of mouth subtly lifted in confident humor, alert engaged gaze checking appearance.',
  },

  // Auxiliary expressions
  {
    id: 'exp_sleepy_relaxed_smile',
    name: 'Sleepy Relaxed Micro-Smile (Cozy & Warm)',
    description: 'Effortless cozy half-smile with relaxed eyelids, projecting calm morning tranquility and relaxed indoor contentment.',
    microExpression: 'Softly relaxed lips, subtle crinkle around eyes, peaceful resting facial muscle tone.',
  },
  {
    id: 'exp_calm_neutral_direct',
    name: 'Calm Direct Gaze at Smartphone Screen',
    description: 'Comfortable, candid gaze looking directly into the phone front camera or screen preview without tense posing.',
    microExpression: 'Neutral relaxed mouth, quiet observant dark eyes with soft room catchlights.',
  },
  {
    id: 'exp_candid_glance_away',
    name: 'Candid Gaze (Glancing Slightly Away)',
    description: 'Eyes directed gently off-camera, captured in an unposed personal moment.',
    microExpression: 'Unrehearsed introspective glance, authentic spontaneous phone snapshot.',
  },
  {
    id: 'exp_playful_smirk_head_tilt',
    name: 'Playful Half-Smirk with Head Tilt',
    description: 'Gentle playful smirk with head tilted slightly, informal and friendly.',
    microExpression: 'One corner of mouth lifted in easy humor, natural relaxed cheek contour.',
  },
];

export const SAUDI_BEDROOM_DETAILS: SaudiBedroomDetailOption[] = [
  {
    id: 'detail_split_ac',
    name: 'Ordinary contemporary bedroom, a white split air conditioner mounted on the wall in the soft-focus background.',
    description: 'Ordinary contemporary bedroom, a white split air conditioner mounted on the wall in the soft-focus background.',
  },
  {
    id: 'detail_chiffon_curtains',
    name: 'Modern bedroom interior, layered sheer chiffon curtains over the window in the background.',
    description: 'Modern bedroom interior, layered sheer chiffon curtains over the window in the background.',
  },
  {
    id: 'detail_wardrobe_closet',
    name: 'Lived-in bedroom setting, a wooden wardrobe closet visible in the background.',
    description: 'Lived-in bedroom setting, a wooden wardrobe closet visible in the background.',
  },
];

